### ISSUE TITLE
Sept 21 - DFD Comments

### ISSUE THREAD

**Issue by germonprez** [mjames940/A1-ISQA3420#13]
Overall, looking good. One comment: 

1) Software Package License Results that are going to the DB --should be--> Software Package License and Vulnerability Results. 

Easy fix.

**Comment by mjames940** [comment]
![dfd updated 9-21](https://cloud.githubusercontent.com/assets/21317641/18736212/6d95121a-804a-11e6-8302-15368c96d0ed.PNG)
